name: PlatformIO CI

on:
  push:

jobs:
  job_build_modulecode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: ${{ runner.os }}-pipenv-

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Create Output folder
      run: |
        mkdir -p ~/OUTPUT
        mkdir -p ~/OUTPUT/Controller
        mkdir -p ~/OUTPUT/Modules/HEX
        mkdir -p ~/OUTPUT/Modules/BIN
        mkdir -p ./ESPController/data/avr
		

    - name: Build code for modules
      run: pio run --project-dir=./ATTINYCellModule --project-conf=./ATTINYCellModule/platformio.ini

    - name: Copy output
      run: |
        cp ./ATTINYCellModule/.pio/build/V*/*.hex ~/OUTPUT/Modules/HEX/
        cp ./ATTINYCellModule/.pio/build/V*/*.bin ~/OUTPUT/Modules/BIN/

    - name: Build code for ESP32 controller
      run: pio run --project-dir=./ESPController --environment esp32-devkitc --project-conf=./ESPController/platformio.ini

    - name: Copy output
      run: |
        cp ./ESPController/.pio/build/esp32-devkitc/diybms_controller_firmware_espressif32_esp32-devkitc.bin ~/OUTPUT/Controller/
        cp ./ESPController/data/avr/manifest.json ~/OUTPUT/Modules/

    - name: Build File System Image for ESP32
      run: pio run --project-dir=./ESPController --target buildfs --environment esp32-devkitc

    - name: Copy output
      run: |
        cp ./ESPController/.pio/build/esp32-devkitc/diybms_controller_filesystemimage_espressif32_esp32-devkitc.bin ~/OUTPUT/Controller/

    - name: Publish Artifacts 1
      uses: actions/upload-artifact@v2
      with:
        name: DIYBMS-Compiled
        path: ~/OUTPUT
        if-no-files-found: error

  job_zip_code:
    runs-on: ubuntu-latest
    needs: [job_build_modulecode]
    steps:
    - name: Download artifact DIYBMS-Compiled
      uses: actions/download-artifact@v2
      with:
        name: DIYBMS-Compiled

    - name: Display structure of downloaded files
      run: ls -R
  
    - name: ZIP output for release
      run: |
        zip --junk-paths release.zip ./esp32-devkitc/diybms_controller_firmware_espressif32_esp32-devkitc.bin
        zip --junk-paths release.zip ./esp32-devkitc/diybms_controller_filesystemimage_espressif32_esp32-devkitc.bin
        zip --junk-paths release.zip ./ESPController/data/avr/manifest.json
        zip --junk-paths release.zip ./ATTINYCellModule/V*/*.hex

    - name: Get current date
      id: date
      run: echo "dt=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

    - name: Display structure of downloaded files
      run: mv release.zip release_${{ env.dt }}.zip

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DIYBMS-Release-Artifact-${{ env.dt }}
        path: ./release_${{ env.dt }}.zip
        if-no-files-found: error
	  
    - name: Create Release Files on MASTER branch only
      id: create_release
      uses: actions/create-release@v1
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: Tag-${{ env.dt }}
        release_name: Release-${{ env.dt }}
        body: |
          Automatically generated release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./release_${{ env.dt }}.zip
        asset_name: Compiled_Firmware_${{ env.dt }}.zip
        asset_content_type: application/zip
